### ISSUE TITLE
Use correct syntax for template literals

### ISSUE THREAD

**Issue by the-codingninja** [thakursaurabh1998/portfoliov2.0#1]
Yes this is my Github account :smiley: 

An interesting tutorial for you about template literal - http://exploringjs.com/es6/ch_template-literals.html

Issues are the best way to communicate on Github.

BTW Have a nice weekend :100:

**Comment by the-codingninja** [comment]
Yes that tutorial thing was a joke 

I know you dont need it :smile:

**Comment by thakursaurabh1998** [comment]
As it looks there is a problem in the typed.js library that I used which doesn't make use of backticks.
I have reported the error to the owner and you can see and follow the issue [here](https://github.com/mattboldt/typed.js/issues/357) @ms10398

**Comment by the-codingninja** [comment]
Okay the I will close the issue 

As its a issue in the dependency and the purpose of the issue is resolved 

:wink: I hope you got to know what I mean
